
var tipuesearch = {"pages": [
     {"title": "Tipue", "text": "", "tags": "jQuery HTML5 CSS", "url": "http://www.tipue.com"},
     {"title": "Tipue Search, a site search engine jQuery plugin", "text": "Tipue Search is a site search engine jQuery plugin. It's free, open source, responsive and fast. Tipue Search only needs a browser that supports jQuery. It doesn't need MySQL or similar. In Static mode it doesn't even need a web server.", "tags": "JavaScript", "url": "http://www.tipue.com/search"},
     {"title": "Peppa Pig", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Animales", "url": "http://gruporuz/marcas.html"},
     {"title": "My Little Pony", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Animales", "url": "http://gruporuz/marcas.html"},
    {"title": "Fryzzys", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "ty", "url": "http://gruporuz/marcas.html"},
    {"title": "Beanie Boos", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "ty", "url": "http://gruporuz/marcas.html"},  
     {"title": "Chuck and Friends", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "hasbro", "url": "http://gruporuz/marcas.html"},  
    {"title": "Plants vs Zombies", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "juego", "url": "http://gruporuz/marcas.html"},
     {"title": "Minecraft", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "juego", "url": "http://gruporuz/marcas.html"},
    {"title": "World of Nintendo", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "juego", "url": "http://gruporuz/marcas.html"},
    {"title": "Halo 5", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "juego", "url": "http://gruporuz/marcas.html"},
    {"title": "Assasins Creed", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "juego", "url": "http://gruporuz/marcas.html"},
     {"title": "Game of Thrones", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "serie", "url": "http://gruporuz/marcas.html"},
     {"title": "The Walking Dead", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "serie", "url": "http://gruporuz/marcas.html"},
     {"title": "The Simpsons", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "caricatura", "url": "http://gruporuz/marcas.html"},
     {"title": "Bob Esponja", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "caricatura", "url": "http://gruporuz/marcas.html"},
    {"title": "Leap Frog", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "juego", "url": "http://gruporuz/marcas.html"},
     {"title": "TMNT", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "caricatura", "url": "http://gruporuz/marcas.html"},
    {"title": "Miles del Mañana", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "miles del mañana", "url": "http://gruporuz/marcas.html"},
     {"title": "Mickey Mouse", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "mickey mouse", "url": "http://gruporuz/marcas.html"},
     {"title": "Minnie Mouse", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "minnie mouse", "url": "http://gruporuz/marcas.html"},
     {"title": "Princesas", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "disney", "url": "http://gruporuz/marcas.html"},
     {"title": "Hadas", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "disney", "url": "http://gruporuz/marcas.html"},
     {"title": "Star Wars", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "disney", "url": "http://gruporuz/marcas.html"},
     {"title": "Marvel", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "avengers", "url": "http://gruporuz/marcas.html"},
     {"title": "Marvel", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "capitan america", "url": "http://gruporuz/marcas.html"},
     {"title": "Marvel", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "spider man", "url": "http://gruporuz/marcas.html"},
     {"title": "Marvel", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "ant man", "url": "http://gruporuz/marcas.html"},
     {"title": "Hello Kity", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "hello kity", "url": "http://gruporuz/marcas.html"},
    {"title": "Chococat", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "chococat", "url": "http://gruporuz/marcas.html"},
    {"title": "Mi villano Favorito", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "mi villano favorito", "url": "http://gruporuz/marcas.html"},
    {"title": "The Secret Life of Pets", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "The Secret Life of Pets", "url": "http://gruporuz/marcas.html"},
    {"title": "Jurassic World", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Jurassic World", "url": "http://gruporuz/marcas.html"},
     {"title": "Barbie", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Barbie", "url": "http://gruporuz/marcas.html"},
    {"title": "Monster High", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Monster High", "url": "http://gruporuz/marcas.html"},
     {"title": "Ever After High", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Ever After High", "url": "http://gruporuz/marcas.html"},
     {"title": "Polly Pocket", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Polly Pocket", "url": "http://gruporuz/marcas.html"},
    {"title": "Max Steel", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Max Steel", "url": "http://gruporuz/marcas.html"},
    {"title": "Thomas and Friends", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Thomas and Friends", "url": "http://gruporuz/marcas.html"},
     {"title": "Blaze", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Blaze", "url": "http://gruporuz/marcas.html"},
    {"title": "Transformers", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Transformers", "url": "http://gruporuz/marcas.html"},
     {"title": "Ben 10", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Ben 10", "url": "http://gruporuz/marcas.html"},
    {"title": "ID", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "ID", "url": "http://gruporuz/marcas.html"},
     {"title": "Distroller", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Distroller", "url": "http://gruporuz/marcas.html"},
    {"title": "Tokidoki", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Tokidoki", "url": "http://gruporuz/marcas.html"},
     {"title": "Corazón de Melón", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "Corazon de Melón", "url": "http://gruporuz/marcas.html"},
    {"title": "Real Madrid", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "futbol", "url": "http://gruporuz/marcas.html"},
     {"title": "Barcelona", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "futbol", "url": "http://gruporuz/marcas.html"},
     {"title": "América", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "futbol", "url": "http://gruporuz/marcas.html"},
    {"title": "Peluches", "text": "Accesorios de todo tipo para las escuelas, mochilas, estuches, loncheras", "tags": "Productos", "url": "http://gruporuz/productos.html"},
    {"title": "¿Qué hacemos?", "text": "Transformamos los productos comunes en divertidos. Desarrollamos producto diferenciado para cada nicho de mercado.", "tags": "hacemos", "url": "http://gruporuz/"},
    {"title": "Frozen", "text": "En esta sección podrás conocer todas las marcas que manejamos.", "tags": "disney", "url": "http://gruporuz/marcas.html"},
    {"title": "Libro de la Selva", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "disney", "url": "http://gruporuz/marcas.html"},
     {"title": "Alicia en el País de las Maravillas", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "alicia", "url": "http://gruporuz/marcas.html"},
     {"title": "Buscando a Dory", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "disney", "url": "http://gruporuz/marcas.html"},
     {"title": "Cars", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "disney", "url": "http://gruporuz/marcas.html"},
     {"title": "Toy Story", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "disney", "url": "http://gruporuz/marcas.html"},
    {"title": "Un gran Dinosaurio", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "un gran dinosaurio", "url": "http://gruporuz/marcas.html"},
    {"title": "Grandes Heroes", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "grandes heroes", "url": "http://gruporuz/marcas.html"},
    {"title": "The Lion Guard", "text": "En esta sección podrás conocer todas las marcas que manejamos.","tags": "disney", "url": "http://gruporuz/marcas.html"},
    {"title": "Promocionales", "text": "Accesorios de todo tipo para las escuelas, mochilas, estuches, loncheras", "tags": "Productos", "url": "http://gruporuz/productos.html"},
    {"title": "Peluches", "text": "Accesorios de todo tipo para las escuelas, mochilas, estuches, loncheras", "tags": "Productos", "url": "http://gruporuz/productos.html"},
    {"title": "Disfraces", "text": "Accesorios de todo tipo para las escuelas, mochilas, estuches, loncheras", "tags": "Productos", "url": "http://gruporuz/productos.html"},
    {"title": "Muñecas", "text": "Accesorios de todo tipo para las escuelas, mochilas, estuches, loncheras", "tags": "Productos", "url": "http://gruporuz/productos.html"},
    {"title": "Juguetes", "text": "Accesorios de todo tipo para las escuelas, mochilas, estuches, loncheras", "tags": "Productos", "url": "http://gruporuz/productos.html"},
     {"title": "Productos", "text": "Accesorios de todo tipo para las escuelas, mochilas, estuches, loncheras", "tags": "Productos", "url": "http://gruporuz/productos.html"},
    {"title": "Backpacks y portalaptops", "text": "Nuestra línea de Backpacks disponibles en tamaño kinder y primaría, así como las portalaptops y fundas más funcionales, modernas y con tu personaje favorito.", "tags": "Productos", "url": "http://gruporuz/productos.html"},
     {"title": "Loncheras", "text": "Las loncheras más divertidas, para el regreso a clase", "tags": "loncheras", "url": "http://gruporuz/productos.html"},
     {"title": "Tipue Search Documentation", "text": "Tipue Search is a site search engine jQuery plugin. It's free, open source and responsive. Tipue Search uses various modes for loading content. Static mode uses a JavaScript object, while JSON mode uses JSON. Live mode grabs content from a list of pages dynamically.", "tags": "docs", "url": "http://www.tipue.com/search/docs"},     
     {"title": "Tipue Search Static mode demo", "text": "Tipue Search is a site search engine jQuery plugin. This is a demo of Static mode. Enter tipue into the search box above.", "tags": "", "url": "http://www.tipue.com/search/demos/static"},
     {"title": "Tipue Search Live mode demo", "text": "Tipue Search is a site search engine jQuery plugin. This is a demo of Live mode. Enter tipue into the search box above.", "tags": "", "url": "http://www.tipue.com/search/demos/live"},
     {"title": "Tipue jQuery plugins Support", "text": "If you're stuck we offer a range of flexible support plans for our jQuery plugins.", "tags": "", "url": "http://www.tipue.com/support"},
     {"title": "Tipr, a small and simple jQuery tooltip plugin", "text": "Tipr is a small and simple jQuery tooltip plugin. It's free and open source. Tipr displays attractive tooltips, and it's a shade under 4KB, CSS included.", "tags": "JavaScript", "url": "http://www.tipue.com/tipr"},
     {"title": "The Tipue blog", "text": "An occasional blog covering CSS, web development, etc.", "tags": "HTML5", "url": "http://www.tipue.com/?d=2"},
     {"title": "About Tipue", "text": "Tipue is a small web development studio based in North London. We've been around for well over a decade. We design innovative add-ins, plugins, code and features with heavy-duty Perl, MySQL and jQuery.", "tags": "", "url": "http://www.tipue.com/about"},     
     {"title": "The Tipue blog - The complete guide to centering a div", "text": "Every new developer inevitably finds that centering a div isn't as obvious as you'd expect. Centering what's inside a div is easy enough by giving the text-align property a value of center, but then things tend to get a bit sticky. When you get to centering a div vertically, you can end up in a world of CSS hurt.", "tags": "HTML", "url": "http://www.tipue.com/blog/center-a-div"},
     {"title": "The Tipue blog - Native HTML5 autocomplete with input list", "text": "This article shows how with the HTML5 input list attribute and datalist element you can easily set up an input box with a custom autocomplete without jQuery, JavaScript or similar.", "tags": "", "url": "http://www.tipue.com/blog/input-list"},
     {"title": "The Tipue blog - The really simple guide to z-index", "text": "The CSS z-index property often trips up new and even experienced developers. The aim of this article is to boil down a somewhat-complex specification to 3 major points, which should ease most z-index pain.", "tags": "", "url": "http://www.tipue.com/z-index"}
]};



